

ALTER TABLE sc_tmp.mbarang
add column kdtax character(50),
add column originalno character(100),
add column satuantax CHARACTER(30),
add column volume numeric(18,2),
add column berat numeric(18,2),
add column gw numeric(18,2),
add column psize numeric(18,2),
add column tsize numeric(18,2),
add column lokasireff CHARACTER(50),
add column idgolonganbarang character(20),
add column idjenisproduk character(20),
add column idkelompokbarang character(20),
add column idprincipal character(20),
add column ppersediaan CHARACTER(20),
add column psj CHARACTER(20),
add column salesakun CHARACTER(20),
add column pcogs CHARACTER(20),
add column phpproduksi CHARACTER(20),
add column pjasa CHARACTER(20),
add column pwaste CHARACTER(20),
add column discontinue CHARACTER(6),
add column issn CHARACTER(6);


ALTER TABLE sc_mst.mbarang
add column kdtax character(50),
add column originalno character(100),
add column satuantax CHARACTER(30),
add column volume numeric(18,2),
add column berat numeric(18,2),
add column gw numeric(18,2),
add column psize numeric(18,2),
add column tsize numeric(18,2),
add column lokasireff CHARACTER(50),
add column idgolonganbarang character(20),
add column idjenisproduk character(20),
add column idkelompokbarang character(20),
add column idprincipal character(20),
add column ppersediaan CHARACTER(20),
add column psj CHARACTER(20),
add column salesakun CHARACTER(20),
add column pcogs CHARACTER(20),
add column phpproduksi CHARACTER(20),
add column pjasa CHARACTER(20),
add column pwaste CHARACTER(20),
add column discontinue CHARACTER(6),
add column issn CHARACTER(6);
